# Generated by Django 5.1.7 on 2025-03-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrierApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_faculty',
            field=models.BooleanField(default=False),
        ),
    ]
