# Generated by Django 5.1.7 on 2025-03-14 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarrierApp', '0003_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_url',
            field=models.URLField(null=True),
        ),
    ]
