# Generated by Django 5.1.7 on 2025-03-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['stream', 'course'],
            },
        ),
    ]
